package com.chasmet.recettemonsieurcuisine;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import java.text.Normalizer;
import java.util.*;

public class MainActivity extends Activity {
 private final List<Recipe> allRecipes=new ArrayList<>(); private LinearLayout countryFilters,categoryFilters,recipeContainer; private TextView resultCount,catalogInfo; private EditText search; private Button tabSelection,tabComplete; private String selectedCountry="all",selectedCategory="all"; private boolean favoritesOnly=false,completeMode=false; private SharedPreferences prefs;
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);prefs=getSharedPreferences("recipe_prefs",MODE_PRIVATE);countryFilters=findViewById(R.id.countryFilters);categoryFilters=findViewById(R.id.categoryFilters);recipeContainer=findViewById(R.id.recipeContainer);resultCount=findViewById(R.id.resultCount);catalogInfo=findViewById(R.id.catalogInfo);search=findViewById(R.id.search);tabSelection=findViewById(R.id.tabSelection);tabComplete=findViewById(R.id.tabComplete);allRecipes.addAll(RecipeRepository.loadAll(this));buildCountryFilters();buildCategoryFilters();tabSelection.setOnClickListener(v->{completeMode=false;refreshTabs();renderRecipes();});tabComplete.setOnClickListener(v->{completeMode=true;refreshTabs();renderRecipes();});refreshTabs();search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){} public void onTextChanged(CharSequence s,int st,int b,int c){renderRecipes();} public void afterTextChanged(Editable e){}});renderRecipes();}
 private void refreshTabs(){Ui.setFilterSelected(tabSelection,!completeMode);Ui.setFilterSelected(tabComplete,completeMode);catalogInfo.setText(completeMode?"Catalogue complet • "+allRecipes.size()+" recettes guidées":"Les 25 recettes incontournables de chaque pays");}
 @Override protected void onResume(){super.onResume();if(recipeContainer!=null)renderRecipes();}
 private void buildCountryFilters(){countryFilters.removeAllViews();addCountryFilter("all","🌍 Toutes");Map<String,String> m=new LinkedHashMap<>();for(Recipe r:allRecipes)m.put(r.country,r.flag+" "+r.countryLabel);for(Map.Entry<String,String>e:m.entrySet())addCountryFilter(e.getKey(),e.getValue());Button fav=Ui.filterButton(this,"♥ Favoris");fav.setOnClickListener(v->{favoritesOnly=!favoritesOnly;Ui.setFilterSelected(fav,favoritesOnly);renderRecipes();});countryFilters.addView(fav);}
 private void addCountryFilter(String key,String label){Button x=Ui.filterButton(this,label);x.setTag(key);x.setOnClickListener(v->{selectedCountry=key;for(int i=0;i<countryFilters.getChildCount();i++){View c=countryFilters.getChildAt(i);if(c instanceof Button&&c.getTag()!=null)Ui.setFilterSelected((Button)c,selectedCountry.equals(c.getTag().toString()));}renderRecipes();});countryFilters.addView(x);if("all".equals(key))Ui.setFilterSelected(x,true);}
 private void buildCategoryFilters(){categoryFilters.removeAllViews();addCat("all","Tout");addCat("plats","🍲 Plats");addCat("entrees","🥗 Entrées");addCat("desserts","🍰 Desserts");}
 private void addCat(String key,String label){Button x=Ui.filterButton(this,label);x.setTag(key);x.setOnClickListener(v->{selectedCategory=key;for(int i=0;i<categoryFilters.getChildCount();i++){View c=categoryFilters.getChildAt(i);if(c instanceof Button)Ui.setFilterSelected((Button)c,selectedCategory.equals(c.getTag()));}renderRecipes();});categoryFilters.addView(x);if("all".equals(key))Ui.setFilterSelected(x,true);}
 private void renderRecipes(){recipeContainer.removeAllViews();String q=normalize(search.getText()==null?"":search.getText().toString());int shown=0;Map<String,Integer> per=new HashMap<>();for(Recipe r:allRecipes){if(!"all".equals(selectedCountry)&&!selectedCountry.equals(r.country))continue;if(!"all".equals(selectedCategory)&&!selectedCategory.equals(r.category))continue;if(favoritesOnly&&!prefs.getBoolean("fav_"+r.id,false))continue;if(!q.isEmpty()&&!normalize(r.title+" "+r.countryLabel+" "+r.categoryLabel+" "+r.description).contains(q))continue;if(!completeMode&&q.isEmpty()&&!favoritesOnly){int n=per.containsKey(r.country)?per.get(r.country):0;if(n>=25)continue;per.put(r.country,n+1);}addRecipeCard(r);shown++;}resultCount.setText(shown+" recettes affichées");if(shown==0)recipeContainer.addView(Ui.text(this,"Aucune recette avec ces filtres.",16,false));}
 private void addRecipeCard(Recipe r){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setBackgroundResource(R.drawable.bg_card);card.setPadding(Ui.dp(this,10),Ui.dp(this,10),Ui.dp(this,10),Ui.dp(this,14));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,Ui.dp(this,14));card.setLayoutParams(cp);ImageView image=new ImageView(this);image.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(this,190)));image.setScaleType(ImageView.ScaleType.CENTER_CROP);AssetImages.load(this,image,r.imagePath);card.addView(image);TextView over=Ui.text(this,r.flag+"  "+r.countryLabel+"  •  "+r.categoryLabel,13,true);over.setTextColor(Color.rgb(182,91,8));Ui.margin(over,6,10,6,0);card.addView(over);TextView name=Ui.text(this,r.title,22,true);Ui.margin(name,6,5,6,0);card.addView(name);TextView meta=Ui.text(this,"⏱ "+(r.prepMinutes+r.cookMinutes)+" min   •   👥 "+r.servings+"   •   "+r.difficulty,14,false);meta.setTextColor(Color.rgb(107,98,90));Ui.margin(meta,6,7,6,0);card.addView(meta);if(prefs.getBoolean("fav_"+r.id,false)){TextView f=Ui.text(this,"♥ Favori",13,true);f.setTextColor(Color.rgb(210,45,45));Ui.margin(f,6,6,6,0);card.addView(f);}card.setOnClickListener(v->{Intent i=new Intent(this,RecipeActivity.class);i.putExtra("assetPath",r.assetPath);startActivity(i);});recipeContainer.addView(card);}
 private static String normalize(String t){return Normalizer.normalize(t,Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ROOT).trim();}
}
